/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyAssignmentComponent {
    'bold': boolean;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyCtaButton {
    'text': string | "default text";
  }
}

declare global {


  interface HTMLMyAssignmentComponentElement extends Components.MyAssignmentComponent, HTMLStencilElement {}
  var HTMLMyAssignmentComponentElement: {
    prototype: HTMLMyAssignmentComponentElement;
    new (): HTMLMyAssignmentComponentElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLMyCtaButtonElement extends Components.MyCtaButton, HTMLStencilElement {}
  var HTMLMyCtaButtonElement: {
    prototype: HTMLMyCtaButtonElement;
    new (): HTMLMyCtaButtonElement;
  };
  interface HTMLElementTagNameMap {
    'my-assignment-component': HTMLMyAssignmentComponentElement;
    'my-component': HTMLMyComponentElement;
    'my-cta-button': HTMLMyCtaButtonElement;
  }
}

declare namespace LocalJSX {
  interface MyAssignmentComponent {
    'bold'?: boolean;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface MyCtaButton {
    'text'?: string | "default text";
  }

  interface IntrinsicElements {
    'my-assignment-component': MyAssignmentComponent;
    'my-component': MyComponent;
    'my-cta-button': MyCtaButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-assignment-component': LocalJSX.MyAssignmentComponent & JSXBase.HTMLAttributes<HTMLMyAssignmentComponentElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'my-cta-button': LocalJSX.MyCtaButton & JSXBase.HTMLAttributes<HTMLMyCtaButtonElement>;
    }
  }
}


